#!/bin/sh

if [ -n "$_ROOT" ]
then
	#_ROOT=/
#else
	if [ -n "$_ROOT_SUPPORTED" ] && [ "$_ROOT_SUPPORTED" -eq "0" ]
	then
		echo -e "Root is not supported - $0"
		exit 2
	fi

	mkdir -p $_ROOT
fi

#_SYSTEM
export _DEBUG _ROOT
