#!/bin/sh

mkdir -p /tmp/downloads

_download() {
	curl -s -L -o $_OUTPUT $uri
	
	_validate
}

_validate() {
	if [ -n "$signature" ]
	then
		sha256 -c $signature $_OUTPUT 2>/dev/null
		return $?
	fi
	
	return 0
}

. $1
_OUTPUT=/tmp/downloads/$filename

if [ -e $_OUTPUT ]
then
	_validate
	if [ "$?" -ne "0" ]
	then
		_download
	fi
else
	_download
fi
