#!/bin/sh

# extract content via tarball OR git clone
_CONFIGURATION_DIRECTORY=$_ROOT/usr/local/etc/walterjwhite/system-configuration/status
_LOG_DIRECTORY=$_ROOT/var/log/walterjwhite
_SYSTEM_IDENTIFICATION=$_ROOT/usr/local/etc/walterjwhite/system

mkdir -p $_CONFIGURATION_DIRECTORY $_LOG_DIRECTORY $(dirname $_SYSTEM_IDENTIFICATION)

export _CONFIGURATION_DIRECTORY=$_CONFIGURATION_DIRECTORY _LOG_DIRECTORY=$_LOG_DIRECTORY _SYSTEM_IDENTIFICATION=$_SYSTEM_IDENTIFICATION

_run() {
  if [ -e $_CONFIGURATION_DIRECTORY/$1 ]
  then
    return
  fi

  _ $2 > $_LOG_DIRECTORY/$1 2>&1

  _RETURN=$?
  case $_RETURN in
    0)
      _complete $1 "Successfully completed - $_RETURN"
      ;;
    1)
      _complete $1 "No activity performed - $_RETURN"
      _ touch $_CONFIGURATION_DIRECTORY/$1
      ;;
    *)
      echo "$1 - Other error - $_RETURN"
      exit $_RETURN

      ;;
  esac
}

_complete() {
  echo "$1 - $2"
  _ touch $_CONFIGURATION_DIRECTORY/$1
}

_snapshot() {
  _SNAPSHOT_NAME=$1
  if [ -n "$_SYSTEM_HASH" ]
  then
    _SNAPSHOT_NAME=${_SYSTEM_HASH}.${_SNAPSHOT_NAME}
  fi

  _EXISTS=$(beadm list -H | grep -c $_SNAPSHOT_NAME)
  if [ "$_EXISTS" -gt "0" ]
  then
    echo "$_SNAPSHOT_NAME exists"
    return
  fi

  _CURRENT_BE=$(beadm list -H | grep "NR" | awk {'print$1'})
  if [ "$_CURRENT_BE" = "$_SNAPSHOT_NAME" ]
  then
    echo "Already on $_CURRENT_BE"
    return
  fi

  _ beadm create $_SNAPSHOT_NAME
  _ beadm activate $_SNAPSHOT_NAME

  _ reboot
}

_run_modules() {
  _INDEX=2

  for _MODULE in $@
  do
    _run ${_INDEX}.${_MODULE} _LIBRARY_PATH_/_APPLICATION_NAME_/setup/${_MODULE}
    _INDEX=$((_INDEX+1))
  done
}
