#!/bin/sh

# ensure logs are cleared out
rm -rf $_LOG_DIRECTORY
mkdir -p $_LOG_DIRECTORY

git branch --no-color --show-current   > $_SYSTEM_IDENTIFICATION
git log --pretty=medium --no-color -1 >> $_SYSTEM_IDENTIFICATION

echo "Configuration Date: $(date)"    >> $_SYSTEM_IDENTIFICATION
