#!/bin/sh

mkdir -p /var/log/walterjwhite

# TODO: make this optional
# required for setting up base packages
dhclient $NET

# bootstrap - required tools for subsequent patches
pkg install -y beadm git gnugrep gsed rsync 2>&1 > /var/log/walterjwhite/0.bootstrap

# configure hostname
echo "hostname=${HOSTNAME}" >> /etc/rc.conf.hostname

# configure the system
PATH=$PATH:/usr/local/bin:/usr/local/sbin
/usr/local/bin/bsdsetup -b=$BRANCH $GIT