#!/bin/sh

. _LIBRARY_PATH_/_APPLICATION_NAME_/setup/libraries/include

_MODULE=chown
_TYPE=d

_chown() {
  for _CHOWN_ in $(find $1 -type f)
  do
    . $_CHOWN_
    chown $options $owner:$group $path

    unset owner group path options
  done
}

for _CHOWN_PATH in $(_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches\
   |xargs -L 1 -I _PATCH_ find _PATCH_ -type $_TYPE\
   |/usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)")
do
  _chown $_CHOWN_PATH
  _HAS_RUN=1
done

_check_run
