#!/bin/sh

_MODULE=files
_TYPE=d

_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches\
  |xargs -L 1 -I _PATCH_ find _PATCH_ -type $_TYPE\
  |/usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)"\
  |xargs -L 1 -I _PATH_ rsync -lmrt _PATH_/ /
