#!/bin/sh

. _LIBRARY_PATH_/_APPLICATION_NAME_/setup/libraries/include

. _LIBRARY_PATH_/_APPLICATION_NAME_/list/go\
	|xargs -L 1 -I _GO_FILE_ _LIBRARY_PATH_/_APPLICATION_NAME_/setup/libraries/go _GO_FILE_
