#!/bin/sh

_ROOT_SUPPORTED=0

. _LIBRARY_PATH_/_APPLICATION_NAME_/setup/libraries/include

_MODULE=groups
_TYPE=d

_add() {
  for _GROUP_PATH_ in $(find $1 -type f)
  do
  	. $_GROUP_PATH_

  	echo -e "###\n#Add Group: $1 $groupName $gid"
  	pw groupadd -n $groupName -g $gid
  done
}

for _GROUPS_PATH in $(_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches\
  |xargs -L 1 -I _PATCH_ find _PATCH_ -type $_TYPE\
  |/usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)")
do
  _add $_GROUPS_PATH
  _HAS_RUN=1
done

_check_run
