#!/bin/sh

. _LIBRARY_PATH_/_APPLICATION_NAME_/setup/libraries/key-value

_ORIGINAL_IFS=$IFS
IFS=$'\n'

_MODULE=rc
_TYPE=d

_TARGET_FILE=/etc/rc.conf

for _RC_PATH in $(_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches | xargs -L 1 -I _PATCH_ find _PATCH_ -type $_TYPE | /usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)"); do
	_key_value $_RC_PATH
done

IFS=$_ORIGINAL_IFS
