#!/bin/sh

_ROOT_SUPPORTED=0

. _LIBRARY_PATH_/_APPLICATION_NAME_/setup/libraries/include

_MODULE=users
_TYPE=d

_add_argument() {
	if [ -n "$2" ]
	then
		_OPTIONS="$_OPTIONS $1 $2"
	fi
}

_add() {
  for _USER_PATH_ in $(find $1 -type f)
  do
	. $_USER_PATH_

	echo -e "###\n#Add User: $1 $username"

	_OPTIONS="-n $username -m"

	_add_argument "-g" "$gid"
	_add_argument "-G" "$grouplist"
	_add_argument "-s" "$shell"
	_add_argument "-u" "$uid"

	pw useradd $_OPTIONS

	# set password
	if [ -n "$password" ]
	then
		chpass -p "$password" $username
	fi
  done
}

for _USERS_PATH in $(_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches\
  |xargs -L 1 -I _PATCH_ find _PATCH_ -type $_TYPE\
  |/usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)")
do
  _add $_USERS_PATH
	_HAS_RUN=1
done

_check_run
