#!/bin/sh

_MODULE=user
_TYPE=f

_add_argument() {
	if [ -n "$2" ]
	then
		_OPTIONS="$_OPTIONS $1 $2"
	fi
}

_add() {
	. $_USER_PATH

	if [ "root" != "$username" ]
	then
		echo -e "###\n#Add User: $_USER_PATH: $username"

		_OPTIONS="-n $username -m"

		_add_argument "-g" "$gid"
		_add_argument "-G" "$grouplist"
		_add_argument "-s" "$shell"
		_add_argument "-u" "$uid"

		pw useradd $_OPTIONS

		unset _OPTIONS
	else
		echo "# Setting shell to $shell for root"
		chsh -s "$shell"
	fi

	# set password
	if [ -n "$password" ]
	then
		echo "# Setting password $shell for $username"
		chpass -p "$password" $username
	fi
}

for _USER_PATH in $(_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches\
  |xargs -L 1 -I _PATCH_ find _PATCH_ -type $_TYPE\
  |/usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)")
do
  _add
done
