#!/bin/sh

_MODULE=add-packages

_LIBRARY_PATH_/_APPLICATION_NAME_/find/patches\
	|xargs -L 1 -I _PATH_ find _PATH_ -type f\
	|/usr/local/bin/grep -P "\\.patch/(${_MODULE}$|.*\\.${_MODULE}$)"\
	|xargs -L 1 -I _PACKAGE_FILE_ /usr/local/bin/grep -Pv "(^#|^#)" _PACKAGE_FILE_\
	|/usr/local/bin/grep -Pv "^$"\
	|sort -u\
	|tr '\n' ' '
